In [1]:
import numpy as np
import pandas as pd
PATH = './data/sample/'
#row_num = 10000000
row_num = None

In [2]:
training = pd.read_csv(PATH + 'training.part', header=None, sep='\t', nrows=row_num)
training.columns = ['click', 'impression', 'displayurl', 'adid', 'advertiserid', 'depth', 
                    'position', 'queryid', 'keywordid', 'titleid', 'descriptionid', 'userid']
training

,click,impression,displayurl,adid,advertiserid,depth,position,queryid,keywordid,titleid,descriptionid,userid
0,0,1,4298118681424644510,7686695,385,3,3,1601,5521,7709,576,490234
1,0,1,4860571499428580850,21560664,37484,2,2,2255103,317,48989,44771,490234
2,0,1,9704320783495875564,21748480,36759,3,3,4532751,60721,685038,29681,490234
3,0,1,13677630321509009335,3517124,23778,3,1,1601,2155,1207,1422,490234
4,0,1,3284760244799604489,20758093,34535,1,1,4532751,77819,266618,222223,490234
5,0,1,10196385171799537224,21375650,36832,2,1,4688625,202465,457316,429545,490234
6,0,1,4203081172173603803,4427028,28647,3,1,4532751,720719,3402221,2663964,490234
7,0,1,4203081172173603803,4428493,28647,2,2,13171922,1493,11658,5668,490234
8,0,1,585474943700910275,20945590,35083,2,1,35143,28111,151695,128782,490234
9,0,1,9684554778607002606,21406020,36943,2,2,4688625,202465,1172072,973354,490234
10,0,1,4860571499428580850,21560710,37484,2,2,4165614,4107,338524,817824,490234
11,0,1,16955212292252911951,20730678,34364,2,2,35143,28111,587150,523997,490234
12,0,1,6912851286990253226,20936539,19186,2,1,34683,61158,81684,373859,490234
13,0,1,11896053558251257301,10295418,28179,3,2,4532751,720719,2405086,2008317,490234
14,0,1,6414307266338366018,21183505,35668,2,2,6259,234,15494,1608,490234
15,0,1,4860571499428580850,21560710,37484,2,2,4165614,4107,338524,572221,490234
16,0,1,11689327222955583742,21021375,27701,3,2,1601,2155,8580,8736,490234
17,0,1,10664591050012752564,20620168,30128,2,1,2255103,419,30486,8760,490234
18,0,1,10664591050012752564,20801912,30128,2,1,13171922,1493,3224,5611,490234
19,0,1,10664591050012752564,20443036,30128,2,1,4165614,31212,201749,170546,490234
20,0,1,10664591050012752564,21392028,30128,2,1,4165614,23791,72800,5369,490234
21,0,1,5755859435141370751,21498278,37333,2,1,12860333,5090,43504,40011,490234
22,0,1,14340390157469404125,4418786,23808,2,2,12860333,5090,3980,4306,490234
23,0,1,15145901239598260039,21894794,37932,2,2,34683,138007,531155,425543,490234
24,0,1,16531381574307507886,22103400,38592,2,1,6259,275,73124,74536,490234
25,0,1,14340390157469404125,10403103,23808,1,1,43742,10284,829,1025,490234
26,0,1,18040112485405760145,20908196,35088,3,1,0,0,43,50,6231944
27,0,1,10349468651765658911,21522776,37422,3,2,0,0,25,4,6231944
28,0,1,12057878999086460853,20157628,27961,3,3,0,0,7,14,6231944
29,0,1,14340390157469404125,9027238,23808,1,1,26769,643,74,94,11180034
...,...,...,...,...,...,...,...,...,...,...,...,...
1799970,1,1,2002143058964984831,20563451,24124,3,1,95706,50790,357342,508728,5459089
1799971,0,1,14340390157469404125,9027923,23808,2,2,12134151,28763,5500,5814,5459089
1799972,0,1,585474943700910275,20945608,35083,1,1,121109,1518,2730,3322,1432800
1799973,0,1,585474943700910275,20945608,35083,3,1,78892,1518,2308,2851,1432800
1799974,0,1,7903914528320191889,21162522,1325,1,1,9420963,68152,22,23,1432800
1799975,0,1,14340390157469404125,6435031,23777,3,2,2413454,50424,57543,56319,1432800
1799976,0,1,12112802856320804600,20622242,29866,1,1,31180,51926,76764,104358,1432800
1799977,0,1,12462462009066863318,10404893,29815,3,3,2413454,10075,78571,93965,1432800
1799978,0,1,14340390157469404125,6435126,23777,2,1,454911,1033,7274,7444,1432800
1799979,0,1,585474943700910275,20945608,35083,2,1,873735,1518,2308,2851,1432800
1799980,0,1,14340390157469404125,3061246,23777,3,2,78892,96505,132552,114670,1432800
1799981,0,1,13242999354365371125,3626541,1137,3,1,2413454,10075,154822,157237,1432800
1799982,0,1,12057878999086460853,20192675,27961,2,2,454911,1033,2201,2567,1432800
1799983,0,1,12057878999086460853,20163122,27961,3,3,78892,1518,33897,36308,1432800
1799984,0,1,3587390226922060392,21115561,23279,1,1,1449,853,6059,6213,1432800
1799985,0,1,12057878999086460853,20163122,27961,2,2,873735,1518,33897,36308,1432800
1799986,0,1,4128633349142478420,20975188,35306,1,1,8612,11909,17977,56078,1432800
1799987,0,1,10349468651765658911,21522776,37422,3,1,0,0,25,4,4444786
1799988,0,1,15785112999276740221,20908196,35088,2,2,0,0,2,5,4444786
1799989,0,1,10349468651765658911,21522776,37422,2,1,0,0,26,28,4444786
1799990,0,2,15785112999276740221,20908196,35088,3,2,0,0,2,5,4444786
1799991,0,2,12057878999086460853,20157587,27961,3,3,0,0,7,14,4444786
1799992,0,1,10349468651765658911,21522776,37422,3,1,0,0,26,28,4444786
1799993,0,1,6263749423537724136,21881309,36720,1,1,36,817,1214,137,19244218
1799994,0,1,375221852289696528,21861963,37842,3,2,475183,67500,2483326,1944832,1737582
1799995,0,1,3558787559009577099,21926392,38024,3,3,167398,13950,359622,293665,1737582
1799996,0,1,14924668103627251390,21965424,38184,3,3,1305459,150,13767,13555,1737582
1799997,0,1,9163350639312619534,22099908,38533,3,1,1305459,13950,23405,27464,1737582
1799998,0,1,84239865823387676,22093619,38474,2,1,720909,54749,656802,529705,1737582
1799999,0,1,9163350639312619534,22099928,38533,3,1,475183,67500,1039957,601799,1737582

In [5]:
training['click'].value_counts()

0     1707305
1       90095
2        2022
3         313
4          99
5          47
6          31
7          21
9          14
8          12
10          6
11          4
12          4
24          3
13          3
18          3
20          2
17          2
63          1
14          1
62          1
19          1
22          1
25          1
31          1
34          1
42          1
43          1
47          1
48          1
60          1
16          1
Name: click, dtype: int64

In [6]:
training['impression'].value_counts()

1      1571798
2       155809
3        38408
4        14674
5         7089
6         4758
7         1803
8         1262
9          869
10         624
11         465
12         413
13         286
14         223
15         184
17         143
16         137
18         126
19         105
21          79
20          76
22          61
24          50
23          47
25          39
27          35
28          34
29          29
26          27
30          27
        ...
169          1
106          1
172          1
178          1
210          1
211          1
212          1
229          1
235          1
108          1
104          1
61           1
82           1
66           1
68           1
72           1
73           1
74           1
76           1
81           1
83           1
103          1
85           1
86           1
89           1
90           1
92           1
93           1
95           1
57           1
Name: impression, Length: 113, dtype: int64

In [7]:
training[training['click'] > 0]['click']

33         2
96         1
97         1
112        1
155        1
167        1
171        1
182        1
190        1
208        1
225        1
234        1
295        1
310        1
317        1
341        1
346        2
373        1
394        1
396        1
490        1
492        1
494        1
498        1
527        1
528        1
586        1
591        1
605        1
611        1
          ..
1799025    1
1799054    1
1799060    1
1799089    1
1799107    1
1799110    1
1799111    1
1799172    1
1799180    1
1799190    1
1799205    1
1799270    1
1799294    1
1799312    1
1799331    1
1799408    1
1799416    1
1799450    1
1799466    1
1799467    1
1799480    1
1799484    1
1799511    1
1799529    1
1799577    1
1799617    1
1799649    1
1799697    1
1799703    1
1799970    1
Name: click, Length: 92695, dtype: int64

In [8]:
training[training['click'] == 0]['click']

0          0
1          0
2          0
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         0
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
20         0
21         0
22         0
23         0
24         0
25         0
26         0
27         0
28         0
29         0
          ..
1799969    0
1799971    0
1799972    0
1799973    0
1799974    0
1799975    0
1799976    0
1799977    0
1799978    0
1799979    0
1799980    0
1799981    0
1799982    0
1799983    0
1799984    0
1799985    0
1799986    0
1799987    0
1799988    0
1799989    0
1799990    0
1799991    0
1799992    0
1799993    0
1799994    0
1799995    0
1799996    0
1799997    0
1799998    0
1799999    0
Name: click, Length: 1707305, dtype: int64

In [9]:
training.loc[training['click'] > 0, 'click'] = 1

In [10]:
training['click'].value_counts()

0    1707305
1      92695
Name: click, dtype: int64

In [11]:
training

,click,impression,displayurl,adid,advertiserid,depth,position,queryid,keywordid,titleid,descriptionid,userid
0,0,1,4298118681424644510,7686695,385,3,3,1601,5521,7709,576,490234
1,0,1,4860571499428580850,21560664,37484,2,2,2255103,317,48989,44771,490234
2,0,1,9704320783495875564,21748480,36759,3,3,4532751,60721,685038,29681,490234
3,0,1,13677630321509009335,3517124,23778,3,1,1601,2155,1207,1422,490234
4,0,1,3284760244799604489,20758093,34535,1,1,4532751,77819,266618,222223,490234
5,0,1,10196385171799537224,21375650,36832,2,1,4688625,202465,457316,429545,490234
6,0,1,4203081172173603803,4427028,28647,3,1,4532751,720719,3402221,2663964,490234
7,0,1,4203081172173603803,4428493,28647,2,2,13171922,1493,11658,5668,490234
8,0,1,585474943700910275,20945590,35083,2,1,35143,28111,151695,128782,490234
9,0,1,9684554778607002606,21406020,36943,2,2,4688625,202465,1172072,973354,490234
10,0,1,4860571499428580850,21560710,37484,2,2,4165614,4107,338524,817824,490234
11,0,1,16955212292252911951,20730678,34364,2,2,35143,28111,587150,523997,490234
12,0,1,6912851286990253226,20936539,19186,2,1,34683,61158,81684,373859,490234
13,0,1,11896053558251257301,10295418,28179,3,2,4532751,720719,2405086,2008317,490234
14,0,1,6414307266338366018,21183505,35668,2,2,6259,234,15494,1608,490234
15,0,1,4860571499428580850,21560710,37484,2,2,4165614,4107,338524,572221,490234
16,0,1,11689327222955583742,21021375,27701,3,2,1601,2155,8580,8736,490234
17,0,1,10664591050012752564,20620168,30128,2,1,2255103,419,30486,8760,490234
18,0,1,10664591050012752564,20801912,30128,2,1,13171922,1493,3224,5611,490234
19,0,1,10664591050012752564,20443036,30128,2,1,4165614,31212,201749,170546,490234
20,0,1,10664591050012752564,21392028,30128,2,1,4165614,23791,72800,5369,490234
21,0,1,5755859435141370751,21498278,37333,2,1,12860333,5090,43504,40011,490234
22,0,1,14340390157469404125,4418786,23808,2,2,12860333,5090,3980,4306,490234
23,0,1,15145901239598260039,21894794,37932,2,2,34683,138007,531155,425543,490234
24,0,1,16531381574307507886,22103400,38592,2,1,6259,275,73124,74536,490234
25,0,1,14340390157469404125,10403103,23808,1,1,43742,10284,829,1025,490234
26,0,1,18040112485405760145,20908196,35088,3,1,0,0,43,50,6231944
27,0,1,10349468651765658911,21522776,37422,3,2,0,0,25,4,6231944
28,0,1,12057878999086460853,20157628,27961,3,3,0,0,7,14,6231944
29,0,1,14340390157469404125,9027238,23808,1,1,26769,643,74,94,11180034
...,...,...,...,...,...,...,...,...,...,...,...,...
1799970,1,1,2002143058964984831,20563451,24124,3,1,95706,50790,357342,508728,5459089
1799971,0,1,14340390157469404125,9027923,23808,2,2,12134151,28763,5500,5814,5459089
1799972,0,1,585474943700910275,20945608,35083,1,1,121109,1518,2730,3322,1432800
1799973,0,1,585474943700910275,20945608,35083,3,1,78892,1518,2308,2851,1432800
1799974,0,1,7903914528320191889,21162522,1325,1,1,9420963,68152,22,23,1432800
1799975,0,1,14340390157469404125,6435031,23777,3,2,2413454,50424,57543,56319,1432800
1799976,0,1,12112802856320804600,20622242,29866,1,1,31180,51926,76764,104358,1432800
1799977,0,1,12462462009066863318,10404893,29815,3,3,2413454,10075,78571,93965,1432800
1799978,0,1,14340390157469404125,6435126,23777,2,1,454911,1033,7274,7444,1432800
1799979,0,1,585474943700910275,20945608,35083,2,1,873735,1518,2308,2851,1432800
1799980,0,1,14340390157469404125,3061246,23777,3,2,78892,96505,132552,114670,1432800
1799981,0,1,13242999354365371125,3626541,1137,3,1,2413454,10075,154822,157237,1432800
1799982,0,1,12057878999086460853,20192675,27961,2,2,454911,1033,2201,2567,1432800
1799983,0,1,12057878999086460853,20163122,27961,3,3,78892,1518,33897,36308,1432800
1799984,0,1,3587390226922060392,21115561,23279,1,1,1449,853,6059,6213,1432800
1799985,0,1,12057878999086460853,20163122,27961,2,2,873735,1518,33897,36308,1432800
1799986,0,1,4128633349142478420,20975188,35306,1,1,8612,11909,17977,56078,1432800
1799987,0,1,10349468651765658911,21522776,37422,3,1,0,0,25,4,4444786
1799988,0,1,15785112999276740221,20908196,35088,2,2,0,0,2,5,4444786
1799989,0,1,10349468651765658911,21522776,37422,2,1,0,0,26,28,4444786
1799990,0,2,15785112999276740221,20908196,35088,3,2,0,0,2,5,4444786
1799991,0,2,12057878999086460853,20157587,27961,3,3,0,0,7,14,4444786
1799992,0,1,10349468651765658911,21522776,37422,3,1,0,0,26,28,4444786
1799993,0,1,6263749423537724136,21881309,36720,1,1,36,817,1214,137,19244218
1799994,0,1,375221852289696528,21861963,37842,3,2,475183,67500,2483326,1944832,1737582
1799995,0,1,3558787559009577099,21926392,38024,3,3,167398,13950,359622,293665,1737582
1799996,0,1,14924668103627251390,21965424,38184,3,3,1305459,150,13767,13555,1737582
1799997,0,1,9163350639312619534,22099908,38533,3,1,1305459,13950,23405,27464,1737582
1799998,0,1,84239865823387676,22093619,38474,2,1,720909,54749,656802,529705,1737582
1799999,0,1,9163350639312619534,22099928,38533,3,1,475183,67500,1039957,601799,1737582

In [12]:
train = training.drop(['impression', 'displayurl', 'advertiserid', 'depth', 'titleid', 'descriptionid'], axis=1)
train

         click      adid  position   queryid  keywordid    userid
0            0   7686695         3      1601       5521    490234
1            0  21560664         2   2255103        317    490234
2            0  21748480         3   4532751      60721    490234
3            0   3517124         1      1601       2155    490234
4            0  20758093         1   4532751      77819    490234
5            0  21375650         1   4688625     202465    490234
6            0   4427028         1   4532751     720719    490234
7            0   4428493         2  13171922       1493    490234
8            0  20945590         1     35143      28111    490234
9            0  21406020         2   4688625     202465    490234
10           0  21560710         2   4165614       4107    490234
11           0  20730678         2     35143      28111    490234
12           0  20936539         1     34683      61158    490234
13           0  10295418         2   4532751     720719    490234
14           0  21183505         2      6259        234    490234
15           0  21560710         2   4165614       4107    490234
16           0  21021375         2      1601       2155    490234
17           0  20620168         1   2255103        419    490234
18           0  20801912         1  13171922       1493    490234
19           0  20443036         1   4165614      31212    490234
20           0  21392028         1   4165614      23791    490234
21           0  21498278         1  12860333       5090    490234
22           0   4418786         2  12860333       5090    490234
23           0  21894794         2     34683     138007    490234
24           0  22103400         1      6259        275    490234
25           0  10403103         1     43742      10284    490234
26           0  20908196         1         0          0   6231944
27           0  21522776         2         0          0   6231944
28           0  20157628         3         0          0   6231944
29           0   9027238         1     26769        643  11180034
...        ...       ...       ...       ...        ...       ...
1799970      1  20563451         1     95706      50790   5459089
1799971      0   9027923         2  12134151      28763   5459089
1799972      0  20945608         1    121109       1518   1432800
1799973      0  20945608         1     78892       1518   1432800
1799974      0  21162522         1   9420963      68152   1432800
1799975      0   6435031         2   2413454      50424   1432800
1799976      0  20622242         1     31180      51926   1432800
1799977      0  10404893         3   2413454      10075   1432800
1799978      0   6435126         1    454911       1033   1432800
1799979      0  20945608         1    873735       1518   1432800
1799980      0   3061246         2     78892      96505   1432800
1799981      0   3626541         1   2413454      10075   1432800
1799982      0  20192675         2    454911       1033   1432800
1799983      0  20163122         3     78892       1518   1432800
1799984      0  21115561         1      1449        853   1432800
1799985      0  20163122         2    873735       1518   1432800
1799986      0  20975188         1      8612      11909   1432800
1799987      0  21522776         1         0          0   4444786
1799988      0  20908196         2         0          0   4444786
1799989      0  21522776         1         0          0   4444786
1799990      0  20908196         2         0          0   4444786
1799991      0  20157587         3         0          0   4444786
1799992      0  21522776         1         0          0   4444786
1799993      0  21881309         1        36        817  19244218
1799994      0  21861963         2    475183      67500   1737582
1799995      0  21926392         3    167398      13950   1737582
1799996      0  21965424         3   1305459        150   1737582
1799997      0  22099908         1   1305459      13950   1737582
1799998      0  22093619         1    720909      54749   1737582
1799999      0  22099928         1    475183      67500   1737582

[1800000 rows x 6 columns]

In [143]:
X = training[['adid', 'position', 'queryid', 'keywordid', 'userid']]
y = training['click']

In [137]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
train_onehot = enc.fit_transform(X)

In [178]:
train_onehot

<1800000x1112903 sparse matrix of type '<class 'numpy.float64'>'
	with 9000000 stored elements in Compressed Sparse Row format>

In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_onehot, y, test_size=0.2, random_state=42)

In [148]:
X_train.shape

(1440000, 1112903)

In [149]:
y_train.shape

(1440000,)

In [185]:
clf = MultinomialNB(0.01)
clf.fit(X_train, y_train)

MultinomialNB(alpha=0.01, class_prior=None, fit_prior=True)

In [186]:
#y_pre = model_xgb.predict(X_test)
y_pre = clf.predict(X_test)

In [187]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pre))

              precision    recall  f1-score   support

           0       0.96      0.90      0.93    341286
           1       0.15      0.30      0.20     18714

   micro avg       0.87      0.87      0.87    360000
   macro avg       0.55      0.60      0.56    360000
weighted avg       0.92      0.87      0.89    360000

In [188]:
#prob_pre = model_xgb.predict_proba(X_test)
prob_pre = clf.predict_proba(X_test)

In [189]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pre)

array([[308692,  32594],
       [ 13107,   5607]])

In [190]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, prob_pre[:, 1])

0.7117466274020442